<?php
/**
 * Generates docs/hooks-reference.md by scanning both products for do_action() and apply_filters() calls
 * whose hook name is a string literal starting with "webgram". Run: php scripts/hooks-reference.php
 */

$root  = dirname( __DIR__ );
$scan  = [ 'Webgram Theme' => 'webgram-theme', 'Webgram Core' => 'webgram-core' ];
$skip  = [ '/node_modules/', '/vendor/', '/assets/', '/languages/' ];
$hooks = [];

foreach ( $scan as $product => $dir ) {
	$it = new RecursiveIteratorIterator( new RecursiveDirectoryIterator( "$root/$dir", FilesystemIterator::SKIP_DOTS ) );
	foreach ( $it as $file ) {
		if ( 'php' !== $file->getExtension() ) {
			continue;
		}
		$path = str_replace( $root . '/', '', $file->getPathname() );
		foreach ( $skip as $s ) {
			if ( str_contains( '/' . $path, $s ) ) {
				continue 2;
			}
		}
		$src = (string) file_get_contents( $file->getPathname() );
		if ( ! preg_match_all( '/\b(do_action|apply_filters)\s*\(/', $src, $m, PREG_OFFSET_CAPTURE ) ) {
			continue;
		}
		foreach ( $m[0] as $i => $match ) {
			$open = $match[1] + strlen( $match[0] ) - 1;
			$call = balanced_call( $src, $open );
			if ( null === $call ) {
				continue;
			}
			$parts = split_args( $call );
			$first = trim( (string) array_shift( $parts ) );
			$name  = hook_name( $first );
			if ( null === $name ) {
				continue;
			}
			$type = 'do_action' === $m[1][ $i ][0] ? 'action' : 'filter';
			$args = trim( implode( ', ', array_map( 'trim', $parts ) ) );
			$line = substr_count( substr( $src, 0, $match[1] ), "\n" ) + 1;
			$doc  = '';
			$before = substr( $src, 0, $match[1] );
			if ( preg_match( '/\/\*\*\s*(.*?)\s*\*\/\s*$/s', $before, $d ) || preg_match( '/\/\/\s*([^\n]*)\n\s*$/', $before, $d ) ) {
				$doc = trim( (string) preg_replace( '/^\s*\*\s?/m', '', $d[1] ) );
				$doc = (string) preg_replace( '/\s+/', ' ', $doc );
			}
			$hooks[ $product ][ $name ] ??= [ 'type' => $type, 'args' => $args, 'doc' => $doc, 'where' => [] ];
			$hooks[ $product ][ $name ]['where'][] = "$path:$line";
		}
	}
}

/** Returns the text between the opening parenthesis at $open and its balanced close, or null. */
function balanced_call( string $src, int $open ): ?string {
	$depth = 0;
	$len   = strlen( $src );
	$quote = '';
	for ( $i = $open; $i < $len; $i++ ) {
		$ch = $src[ $i ];
		if ( $quote ) {
			if ( '\\' === $ch ) {
				$i++;
			} elseif ( $ch === $quote ) {
				$quote = '';
			}
			continue;
		}
		if ( '\'' === $ch || '"' === $ch ) {
			$quote = $ch;
		} elseif ( '(' === $ch ) {
			$depth++;
		} elseif ( ')' === $ch ) {
			$depth--;
			if ( 0 === $depth ) {
				return substr( $src, $open + 1, $i - $open - 1 );
			}
		}
	}
	return null;
}

/** Splits an argument list on top-level commas. */
function split_args( string $call ): array {
	$parts = [];
	$depth = 0;
	$quote = '';
	$buf   = '';
	$len   = strlen( $call );
	for ( $i = 0; $i < $len; $i++ ) {
		$ch = $call[ $i ];
		if ( $quote ) {
			$buf .= $ch;
			if ( '\\' === $ch ) {
				$buf .= $call[ ++$i ] ?? '';
			} elseif ( $ch === $quote ) {
				$quote = '';
			}
			continue;
		}
		if ( '\'' === $ch || '"' === $ch ) {
			$quote = $ch;
		} elseif ( in_array( $ch, [ '(', '[', '{' ], true ) ) {
			$depth++;
		} elseif ( in_array( $ch, [ ')', ']', '}' ], true ) ) {
			$depth--;
		} elseif ( ',' === $ch && 0 === $depth ) {
			$parts[] = $buf;
			$buf     = '';
			continue;
		}
		$buf .= $ch;
	}
	if ( '' !== trim( $buf ) ) {
		$parts[] = $buf;
	}
	return $parts;
}

/** Turns a hook name expression into a readable name; dynamic parts become {placeholders}. */
function hook_name( string $expr ): ?string {
	if ( preg_match( '/^([\'"])(webgram[^\'"]*)\1$/', $expr, $m ) ) {
		return $m[2];
	}
	if ( ! str_contains( $expr, 'webgram' ) ) {
		return null;
	}
	$name = '';
	foreach ( split_concat( $expr ) as $piece ) {
		$piece = trim( $piece );
		if ( preg_match( '/^([\'"])(.*)\1$/s', $piece, $m ) ) {
			$name .= $m[2];
		} elseif ( preg_match( '/\$this->([a-z_]+)|\$([a-z_]+)|::([A-Z_]+)|->([a-z_]+)\(\)/i', $piece, $m ) ) {
			$name .= '{' . strtolower( $m[1] ?: ( $m[2] ?: ( $m[3] ?: $m[4] ) ) ) . '}';
		} else {
			$name .= '{expr}';
		}
	}
	return str_starts_with( $name, 'webgram' ) ? $name : null;
}

function split_concat( string $expr ): array {
	$parts = [];
	$quote = '';
	$buf   = '';
	$len   = strlen( $expr );
	for ( $i = 0; $i < $len; $i++ ) {
		$ch = $expr[ $i ];
		if ( $quote ) {
			$buf .= $ch;
			if ( $ch === $quote ) {
				$quote = '';
			}
			continue;
		}
		if ( '\'' === $ch || '"' === $ch ) {
			$quote = $ch;
		} elseif ( '.' === $ch ) {
			$parts[] = $buf;
			$buf     = '';
			continue;
		}
		$buf .= $ch;
	}
	$parts[] = $buf;
	return $parts;
}

$out   = [];
$out[] = '# Webgram hooks reference';
$out[] = '';
$out[] = 'Generated by `php scripts/hooks-reference.php`. Do not edit by hand. Theme hooks use the `webgram/area/event` form; Core hooks use `webgram_core/module/event`. Actions are fired with `do_action`, filters with `apply_filters`; the argument list shows what listeners receive (the first filter argument is the value being filtered).';
$out[] = '';
foreach ( $hooks as $product => $list ) {
	ksort( $list );
	$out[] = "## $product (" . count( $list ) . ' hooks)';
	$out[] = '';
	$out[] = '| Hook | Type | Arguments | Where |';
	$out[] = '|------|------|-----------|-------|';
	foreach ( $list as $name => $h ) {
		$args = str_replace( [ "\n", '|' ], [ ' ', '\|' ], preg_replace( '/\s+/', ' ', $h['args'] ) );
		if ( strlen( $args ) > 110 ) {
			$args = substr( $args, 0, 107 ) . '...';
		}
		$where = implode( '<br>', array_map( static fn( $w ) => '`' . $w . '`', array_unique( $h['where'] ) ) );
		$out[] = sprintf( '| `%s` | %s | `%s` | %s |', $name, $h['type'], $args ?: '(none)', $where );
	}
	$out[] = '';
}
file_put_contents( "$root/docs/hooks-reference.md", implode( "\n", $out ) . "\n" );
$total = array_sum( array_map( 'count', $hooks ) );
echo "docs/hooks-reference.md written with $total hooks\n";
